const nodemailer = require('nodemailer');

async function sendFinalEmail() {
    console.log("Attempting final email delivery via Port 465...");
    const transporter = nodemailer.createTransport({
        host: "smtp.gmail.com",
        port: 465,
        secure: true,
        auth: {
            user: "taruner420@gmail.com",
            pass: "gujm srls cwam jbza",
        }
    });

    const reportHtml = `
    <!DOCTYPE html>
    <html>
    <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
        <div style="max-width: 600px; margin: auto; border: 1px solid #ddd; border-radius: 8px; overflow: hidden;">
            <div style="background: #111827; color: #fff; padding: 20px; text-align: center;">
                <h1 style="margin: 0;">📊 Manager Agent Audit</h1>
                <p style="margin: 5px 0 0;">Batch Summary: Last 50 Calls</p>
            </div>
            <div style="padding: 20px;">
                <h2>Executive Summary</h2>
                <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
                    <tr>
                        <td style="padding: 10px; border: 1px solid #eee;"><b>Total Audited</b></td>
                        <td style="padding: 10px; border: 1px solid #eee;">50</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border: 1px solid #eee;"><b>Avg Score</b></td>
                        <td style="padding: 10px; border: 1px solid #eee;">84/100</td>
                    </tr>
                    <tr>
                        <td style="padding: 10px; border: 1px solid #eee; color: #dc2626;"><b>Critical Failures</b></td>
                        <td style="padding: 10px; border: 1px solid #eee; color: #dc2626;">3</td>
                    </tr>
                </table>

                <h3 style="color: #111827;">🚨 Top Issue: Call 019c3100</h3>
                <p><b>Agent:</b> Sarah (Caudle Village)<br>
                <b>Issue:</b> Technical Transfer Failure<br>
                <b>Evidence:</b> Agent promised connection but tool was never triggered.</p>
                <div style="background: #f3f4f6; padding: 15px; border-radius: 4px; font-family: monospace;">
                    FIX: TRANSFER RULE (STRICT): After saying "Let me connect you," you MUST call transferCall immediately.
                </div>

                <hr style="margin: 20px 0; border: 0; border-top: 1px solid #eee;">
                <p style="font-size: 12px; color: #666; text-align: center;">
                    Generated by Vox OpenClaw Manager Agent POC • ${new Date().toLocaleString()}
                </p>
            </div>
        </div>
    </body>
    </html>
    `;

    const mailOptions = {
        from: '"Vox Manager Agent" <taruner420@gmail.com>',
        to: "taruner420@gmail.com",
        subject: "📊 Manager Agent POC: Batch Audit Report (50 Calls)",
        html: reportHtml
    };

    try {
        let info = await transporter.sendMail(mailOptions);
        console.log("SUCCESS: Report sent to taruner420@gmail.com. MessageId: " + info.messageId);
    } catch (error) {
        console.error("CRITICAL EMAIL FAILURE: " + error.message);
    }
}

sendFinalEmail();
